language: ruby
cache: bundler
sudo: false

rvm:
  - 2.2.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - adib.saad@gmail.com
    on_failure: change
    on_success: never
